mobike/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='home'

urlpatterns = [

    path('', views.index, name='index'),
    path('perfil/', views.perfil, name='perfil'),
    path('agregar_tarjeta/', views.agregarTarjetaCredito, name='agregar_tarjeta'),
    path('seleccionar_arriendo/<str:pk>/', views.seleccionarArriendo, name='seleccionar_arriendo'),
    path('seleccionar_forma_de_pago/<str:pk>/', views.seleccionarFormaDePago, name='seleccionar_forma_de_pago'),
    path('resumen/<str:pk>', views.resumenViaje, name='resumen'),
    path('pago_finalizado/<str:pk>/', views.generarCodigo, name='pago_finalizado'),
    path('desbloquear/<str:pk>/', views.desbloqueoBicicleta, name='desbloquear'),
    path('bloquear/<str:pk>/', views.bloquearBicicleta, name='bloquear'),
]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mantenedor_usuario.urls')),
    path('home/', include('home.urls')),
]

mobike/home/models.py
from django.db import models
from mantenedor_usuario.models import Usuario


class TarjetaCredito(models.Model):

    dueno = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    numero = models.IntegerField()
    nombre = models.CharField(max_length=200)
    fecha_vencimiento = models.DateField()
    cvv = models.IntegerField()
    tipo = models.CharField(max_length=200)

    objects = models.Manager()

class Bicicleta(models.Model):

    fecha_registro = models.DateField()
    estado = models.BooleanField(default=False)
    codigo = models.CharField(max_length=5, blank=True, null=True)

    objects = models.Manager()

class Viaje(models.Model):

    hora_inicio = models.DateTimeField()
    hora_fin = models.DateTimeField()
    usuario = models.ForeignKey(Usuario, on_delete=models.CASCADE)
    bicicleta = models.ForeignKey(Bicicleta, on_delete=models.CASCADE)

    objects = models.Manager()

class Arriendo(models.Model):

    descripcion = models.CharField(max_length=200)
    precio = models.IntegerField()

    objects = models.Manager()

mobike/home/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from .models import TarjetaCredito
from datetime import date, datetime
from calendar import monthrange
from django.core.validators import EMPTY_VALUES

class CCExpWidget(forms.MultiWidget):
    """ Widget containing two select boxes for selecting the month and year"""
    def decompress(self, value):
        return [value.month, value.year] if value else [None, None]

    def format_output(self, rendered_widgets):
        html = u' / '.join(rendered_widgets)
        return u'<span style="white-space: nowrap">%s</span>' % html


class CCExpField(forms.MultiValueField):
    EXP_MONTH = [(x, x) for x in range(1, 13)]
    EXP_YEAR = [(x, x) for x in range(date.today().year,
                                       date.today().year + 15)]
    default_error_messages = {
        'invalid_month': u'Introduzca un mes valido..',
        'invalid_year': u'Introduzca un año valido.',
    }

    def __init__(self, *args, **kwargs):
        errors = self.default_error_messages.copy()
        if 'error_messages' in kwargs:
            errors.update(kwargs['error_messages'])
        fields = (
            forms.ChoiceField(choices=self.EXP_MONTH,
                error_messages={'invalid': errors['invalid_month']}),
            forms.ChoiceField(choices=self.EXP_YEAR,
                error_messages={'invalid': errors['invalid_year']}),
        )
        super(CCExpField, self).__init__(fields, *args, **kwargs)
        self.widget = CCExpWidget(widgets =
            [fields[0].widget, fields[1].widget])

    def clean(self, value):
        exp = super(CCExpField, self).clean(value)
        if date.today() > exp:
            raise forms.ValidationError(
            "La fecha de expiracion ingresada es del pasado.")
        return exp

    def compress(self, data_list):
        if data_list:
            if data_list[1] in EMPTY_VALUES:
                error = self.error_messages['invalid_year']
                raise forms.ValidationError(error)
            if data_list[0] in EMPTY_VALUES:
                error = self.error_messages['invalid_month']
                raise forms.ValidationError(error)
            year = int(data_list[1])
            month = int(data_list[0])
            # find last day of the month
            day = monthrange(year, month)[1]
            return date(year, month, day)
        return None



class TarjetaCreditoForm(forms.ModelForm):

    expiration = CCExpField(required=True,label= "Fecha de Vencimiento")

    class Meta:

        model = TarjetaCredito
        fields = ('numero','nombre','cvv','expiration')
    
    def __init__(self, *args, **kwargs):

        super(TarjetaCreditoForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})

class CodigoActivacionForm(forms.Form):

    codigo = forms.CharField(label='Codigo de Activación', max_length=5)

    def __init__(self, *args, **kwargs):

        super(CodigoActivacionForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})

mobike/home/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseRedirect
from django.contrib.auth.decorators import login_required, permission_required
from .forms import TarjetaCreditoForm, CodigoActivacionForm
from .models import TarjetaCredito, Bicicleta, Viaje, Arriendo
from django.utils.crypto import get_random_string
# Create your views here.

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def index(request):

    bicicletas = Bicicleta.objects.all()
    request.session['arriendo'] = None
    request.session['bicicleta'] = None
    request.session['tarjeta'] = None

    return render(request,'home/index.html',{'bicicletas':bicicletas})

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def perfil(request):
    pass

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def agregarTarjetaCredito(request):

    form_tarjeta = TarjetaCreditoForm()

    if request.method == 'POST':

        form_tarjeta = TarjetaCreditoForm(data=request.POST)

        print(form_tarjeta.is_valid())
        
        if form_tarjeta.is_valid():

            tipo = form_tarjeta.data['tipo_tarjeta']
            duenio = request.user
            numero = form_tarjeta.cleaned_data['numero']
            fecha_vencimiento = form_tarjeta.cleaned_data['expiration']
            cvv = form_tarjeta.cleaned_data['cvv']
            nombre = form_tarjeta.cleaned_data['nombre']

            tarjeta = TarjetaCredito()
            tarjeta.dueno = duenio
            tarjeta.numero = numero
            tarjeta.fecha_vencimiento = fecha_vencimiento
            tarjeta.cvv = cvv
            tarjeta.nombre = nombre
            tarjeta.tipo = tipo

            tarjeta.save()
        
            return redirect('home:index')

    return render(request, 'home/formulario_tarjeta.html', {'form': form_tarjeta})

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def seleccionarArriendo(request, pk):

    lista_arriendos = Arriendo.objects.all()
    bici = Bicicleta.objects.get(id=pk)
    request.session['bicicleta'] = bici.id

    return render(request, 'home/seleccionar_arriendo.html', {'arriendo':lista_arriendos})

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def seleccionarFormaDePago(request, pk):

    tarjeta = TarjetaCredito.objects.filter(dueno_id=request.user)
    arriendo = Arriendo.objects.get(id=pk)
    request.session['arriendo'] = arriendo.id

    return render(request, 'home/seleccionar_tarjeta.html', {'tarjeta':tarjeta})

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def resumenViaje(request, pk):

    tarjeta = TarjetaCredito.objects.get(id=pk)
    arriendo = Arriendo.objects.get(id=request.session['arriendo'])
    bicicleta = Bicicleta.objects.get(id=request.session['bicicleta'])

    return render(request, 'home/resumen.html', {'tarjeta':tarjeta,'arriendo':arriendo,'bicicleta':bicicleta})

@login_required(login_url='mantenedor_usuario:inicio_sesion')
def generarCodigo(request, pk):

    codigo_activacion = get_random_string(length=5)
    bicicleta = Bicicleta.objects.get(id=pk)
    bicicleta.codigo = codigo_activacion
    bicicleta.save()

    return render(request, 'home/codigo.html', {'cod':codigo_activacion})

def desbloqueoBicicleta(request, pk):

    bici = Bicicleta.objects.get(id=pk)
    errores = False

    if request.method == 'POST':

        codigo_form = CodigoActivacionForm(data=request.POST)

        if codigo_form.is_valid():

            codigo = codigo_form.data['codigo']

            if codigo == bici.codigo:

                bici.estado = True
                bici.codigo = ''
                bici.save()

                return redirect('/home/')
            
            else:

                errores = True
    else:

        codigo_form = CodigoActivacionForm()

    return render(request, 'home/codigo_activacion.html', {'codigo_form': codigo_form,'error':errores})

def bloquearBicicleta(request, pk):

    bicicleta = Bicicleta.objects.get(id=pk)
    bicicleta.estado = False
    bicicleta.save()

    return redirect('/')

mobike/home/templates/home/codigo.html
{% extends 'base.html' %}
{% block head %}

<title>Arriendo de Bicicleta</title>

{% endblock head %}
{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="row">
                                    <div class="col-12 d-flex justify-content-center mb-5">
                                        Gracias por Arrendar.
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-6 d-flex justify-content-left mb-4">
                                        Tu codigo de Activacion es:
                                    </div>
                                    <div class="col-6 d-flex justify-content-center">
                                        {{cod}}
                                    </div>
                                </div>
                                <div class="row mt-12">
                                    <div class="col-12 d-flex justify-content-center">
                                        <button name="button" value="confirmar" class="btn btn-primary" onclick="location.href='{% url 'home:index'%}'">Volver</button>
                                    </div>
                                </div>                             
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}

mobike/home/templates/home/codigo_activacion.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>
    Registro de Tarjeta
</title>
{% endblock head %}

{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">Ingrese Codigo:  {{codigo_form.codigo}}</div>
                                                </div>
                                            </div>
                                            {% if error == True %}
                                                <div class="col-md-12 d-flex justify-content-center alert alert-danger" role="alert"> Codigo Invalido. </div>
                                            {% endif %}
                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Desbloquear"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>
{% endblock content %}

mobike/home/templates/home/formulario_tarjeta.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>
    Registro de Tarjeta
</title>
{% endblock head %}

{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-7">
                                                    <div class="form-group">{{form.nombre.label}} {{form.nombre}} {{form.nombre.errors}}</div>
                                                </div>
                                                <div class="col-md-5">
                                                    <div class="form-group">{{form.cvv.label}} {{form.cvv}} {{form.cvv.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">Numero de Tarjeta {{form.numero}} {{form.numero.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">{{form.expiration.label}} {{form.expiration}} {{form.errors.expiration}}</div>
                                                </div>
                                                <div class="col-md-8">
                                                    <div class="form-check" id="credit_cards">
                                                    Tipo Tarjeta<br><br>
                                                    <label>
                                                    <input type="radio" name="tipo_tarjeta" value="Visa" checked>
                                                    <img src="{% static 'assets/img/visa.jpg' %} " id="visa">
                                                    </label>
                                                    <label>
                                                    <input type="radio" name="tipo_tarjeta" value="Mastercard">
                                                    <img src="{% static 'assets/img/mastercard.jpg' %} " id="mastercard">
                                                    </label>
                                                    <label>
                                                    <input type="radio" name="tipo_tarjeta" value="Amex">
                                                    <img src="{% static 'assets/img/amex.jpg' %} " id="amex">
                                                    </label>
                                                    </div>
                                                </div>
                                            </div>

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Registrar Tarjeta"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>
{% endblock content %}

mobike/home/templates/home/index.html
{% extends 'base.html' %}
{% block head %}

<title>Home</title>

{% endblock head %}
{% block content %}
<br><br><br><br>
            <div class="row">
                <div class="card mt-2 mx-auto p-4 bg-light col-11">
                    <div class="card-body bg-light">

            <table class="table">
            <div><h3 class="d-flex justify-content-center">BICICLETAS</h3></div>
                <tr>
                    <th>ID</th>
                    <th>ESTADO</th>
                    <th>ARRENDAR</th>
                    <th>DESBLOQUEAR</th>
                    <th>FINALIZAR VIAJE</th>
                </tr>

                {% for i in bicicletas %}
                    <tr>
                       <td>{{i.id}}</td>
                        {% if i.estado == True %}
                        <td>Desbloqueado</td>
                        {% else %}
                        <td>Bloqueado</td>
                        {% endif %}
                        <td><button name="button" value="arrendar" class="btn btn-primary" onclick="location.href='{% url 'home:seleccionar_arriendo' i.id %}'">Arrendar</button></td>
                        <td><button name="button" value="desbloquear" class="btn btn-primary" onclick="location.href='{% url 'home:desbloquear' i.id %}'">Desbloquear</button></td>
                        {% if i.estado == True %}
                        <td><button name="button" value="bloquear" class="btn btn-primary" onclick="location.href='{% url 'home:bloquear' i.id %}'">Finalizar Viaje</button></td>
                        {% endif %}                        
                    </tr>

                {% endfor %}
            </table>
                    </div>
                </div>
            </div>
{% endblock content %}

mobike/home/templates/home/resumen.html
{% extends 'base.html' %}
{% block head %}

<title>Arriendo de Bicicleta</title>

{% endblock head %}
{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="row">
                                    <div class="col-12 d-flex justify-content-center mb-5">
                                        Detalle de Arriendo
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-4 d-flex justify-content-left mb-4">
                                        Bicicleta
                                    </div>
                                    <div class="col-8 d-flex justify-content-center">
                                        {{bicicleta.id}}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-4 d-flex justify-content-left mb-4">
                                        Arriendo
                                    </div>
                                    <div class="col-8 d-flex justify-content-center">
                                        {{arriendo.descripcion}}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-4 d-flex justify-content-left mb-4">
                                        Tarjeta de credito
                                    </div>
                                    <div class="col-8 d-flex justify-content-center">
                                        {{tarjeta.numero}} <br> {{tarjeta.tipo}}
                                    </div>
                                </div>
                                <div class="row mt-4">
                                    <div class="col-6 d-flex justify-content-end">
                                        <button name="button" value="confirmar" class="btn btn-primary" onclick="location.href='{% url 'home:pago_finalizado' bicicleta.id %}'">Confirmar</button>
                                    </div>
                                    <div class="col-6 d-flex justify-content-start">
                                        <button name="button" value="cancelar" class="btn btn-primary" onclick="location.href='{% url 'home:index'%}'">Cancelar</button>
                                    </div>
                                </div>                             
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}

mobike/home/templates/home/seleccionar_arriendo.html
{% extends 'base.html' %}
{% block head %}

<title>Arriendo de Bicicleta</title>

{% endblock head %}
{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <table class="table">
                                    <div><h3 class="d-flex justify-content-center">Arriendo</h3></div>
                                    <br>
                                    {% for i in arriendo %}
                                        <tr>
                                        <td>{{i.descripcion}}</td>
                                            <td><button name="button" value="stock" class="btn btn-primary" onclick="location.href='{% url 'home:seleccionar_forma_de_pago' i.id %}'">Seleccionar</button></td>
                                        </tr>

                                    {% endfor %}
                                </table>                            
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}

mobike/home/templates/home/seleccionar_tarjeta.html
{% extends 'base.html' %}
{% block head %}

<title>Arriendo de Bicicleta</title>

{% endblock head %}
{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <table class="table">
                                    <div><h3 class="d-flex justify-content-center">Tarjeta</h3></div>
                                    <br>
                                    {% if tarjeta %}
                                        {% for i in tarjeta %}
                                            <tr>
                                            <td>{{i.numero}}<br>{{i.tipo}}</td>
                                                <td><button name="button" value="stock" class="btn btn-primary" onclick="location.href='{% url 'home:resumen' i.id %}'">Seleccionar</button></td>
                                            </tr>

                                        {% endfor %}
                                    {% endif %}
                                            <tr>
                                            <td>Agregar nueva Tarjeta</td>
                                                <td><button name="button" value="stock" class="btn btn-primary" onclick="location.href='{% url 'home:agregar_tarjeta' %}'">Agregar</button></td>
                                            </tr>

                                </table>                            
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}