mobike/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='home'

urlpatterns = [

    path('', views.index, name='index'),
    path('perfil/', views.perfil, name='perfil'),
    path('agregar_tarjeta/', views.agregarTarjetaCredito, name='agregar_tarjeta'),
    path('seleccionar_arriendo/<str:pk>/', views.seleccionarArriendo, name='seleccionar_arriendo'),
    path('seleccionar_forma_de_pago/<str:pk>/', views.seleccionarFormaDePago, name='seleccionar_forma_de_pago'),
    path('resumen/<str:pk>', views.resumenViaje, name='resumen'),
    path('pago_finalizado/<str:pk>/', views.generarCodigo, name='pago_finalizado'),
    path('desbloquear/<str:pk>/', views.desbloqueoBicicleta, name='desbloquear'),
    path('bloquear/<str:pk>/', views.bloquearBicicleta, name='bloquear'),
]

mobike/mantenedor_usuario/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='mantenedor_usuario'

urlpatterns = [
    path('', views.index, name='index'),
    path('registro/',views.register, name='registro'),
    path('inicio_sesion/',views.login, name='inicio_sesion'),
    path('cerrar_sesion/',views.logout, name='cerrar_sesion'),
    
]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mantenedor_usuario.urls')),
    path('home/', include('home.urls')),
]

mobike/mantenedor_usuario/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

class Usuario(AbstractUser):

    run = models.IntegerField(null=True)
    dv = models.CharField(max_length=1,null=True)

mobike/mantenedor_usuario/forms.py
from django import forms
from django.forms import widgets
from django.forms.models import fields_for_model
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from .models import Usuario
from itertools import cycle

def validate_dv(run):
    reversed_digits = map(int, reversed(str(run)))
    factors = cycle(range(2, 8))
    s = sum(d * f for d, f in zip(reversed_digits, factors))
    return (-s) % 11

class RegistrationForm(UserCreationForm):

    class Meta:

        model = Usuario
        fields = ('username','first_name' ,'last_name' , 'email', 'password1', 'password2', 'run','dv') 

    def clean_dv(self):

        dv = self.cleaned_data.get('dv')

        run = self.cleaned_data.get('run')

        dv2 = validate_dv(run)

        print(dv2,dv)

        if str(dv) != str(dv2):

            raise forms.ValidationError('Ingrese un Rut valido.')
        
        return dv

    def __init__(self, *args, **kwargs):

        super(RegistrationForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})

 
        for field in self.fields.values():
                field.help_text = None

class LoginForm(AuthenticationForm):

    def __init__(self, *args, **kwargs):

        super(LoginForm, self).__init__(*args,**kwargs)

        for field in self.fields:
            
            self.fields[field].widget.attrs.update({'class': 'form-control'})    

mobike/mantenedor_usuario/views.py
from django.shortcuts import render, redirect
from django.http.response import HttpResponse, HttpResponseRedirect
from .forms import RegistrationForm, LoginForm
from django.contrib.auth import login as log_in, logout as log_out
from .auth import AuthenticationEmailBackend
from django.contrib.auth import authenticate
from mantenedor_usuario.models import Usuario


def index(request):

    if not request.user.is_anonymous:
        return redirect('home:index')
    return render(request,'mantenedor_usuario/index.html',{})

def register(request):

    registration_form = RegistrationForm()

    if request.method == "POST":

        registration_form = RegistrationForm(data=request.POST)

        if registration_form.is_valid():

            user = registration_form.save()

            username = registration_form.cleaned_data['username']
            password = registration_form.cleaned_data['password1']

            user = authenticate(username=username,password=password)

            if user is not None:

                log_in(request, user)

                return redirect('mantenedor_usuario:index')


    return render(request, "mantenedor_usuario/register.html", {'registration_form': registration_form})

def login(request):

    login_form = LoginForm()

    if request.method == "POST":
        print('pasa')
        login_form = LoginForm(data=request.POST)

        print(login_form.is_valid())
        if login_form.is_valid():

            username = login_form.cleaned_data['username']
            password = login_form.cleaned_data['password']

            user = authenticate(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('home:index')

            user = AuthenticationEmailBackend(username=username, password=password)

            if user is not None:

                log_in(request, user)

                return redirect('home:index')

    return render(request, 'mantenedor_usuario/login.html',{'login_form':login_form})

def logout(request):

    log_out(request)

    return redirect('mantenedor_usuario:index')

mobike/mantenedor_usuario/templates/mantenedor_usuario/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
<title>Inicio</title>
{% endblock head %}
{% block content %}
        <header class="masthead">
            <div class="container d-flex h-100 align-items-center">
                <div class="mx-auto text-center">
                    <h1 class="mx-auto my-0 text-uppercase">Movilizate con Mobike</h1>
                    <h2 class="text-white-80 mx-auto mt-2 mb-5">Mobike la Reina, una nueva forma de movilizacion</h2>
                </div>
            </div>
        </header>
        <!-- About-->
        <section class="mastsection about-section text-center" id="about">
            <div class="container">
                <div class="row">
                    <div class="col-lg-8 mx-auto">
                        <h2 class="text-white mb-4">¿Que es Mobike?</h2>
                        <p class="text-white-80">
                            Mobike es una solución para la problematica que tiene la comuna de la Reina ultimamente, entregando una
                            opcion saludable para viajar a traves de la comuna mediante el arriendo de bicicletas, puedes<a href="{% url 'mantenedor_usuario:inicio_sesion' %}"> iniciar sesion aquí</a>
                            o <a href="{% url 'mantenedor_usuario:registro' %}"> registrarte aquí.</a>
                        </p>
                    </div>
                </div>
            </div>
        </section>
        <!-- Projects-->
        <section class="projects-section bg-black" id="projects">
        </section>
        <!-- Signup-->
        <section class="signup-section" id="signup">
            <div class="container">
                <div class="row">
                    <div class="col-md-10 col-lg-8 mx-auto text-center">
                        <i class="far fa-paper-plane fa-2x mb-2 text-white"></i>
                        <h2 class="text-white mb-2">Registrate Aquí</h2>
                        <p class="text-white">o inicia sesión</p>
                        <div class="inline d-flex">
                            <button class="btn btn-primary mx-auto" type="button" onclick="location.href='{% url 'mantenedor_usuario:registro' %}'">Registrarse</button>
                                                        <button class="btn btn-primary mx-auto" type="button" onclick="location.href='{% url 'mantenedor_usuario:inicio_sesion' %}'">Inicia Sesion</button>
                        </div>
                    </div>
                </div>
            </div>
        </section>
{% endblock content %}

mobike/mantenedor_usuario/templates/mantenedor_usuario/login.html
{% extends 'base.html' %}

{% block head %}
<title>
    Registro de Usuario
</title>
{% endblock head %}

{% block content %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">Usuario o Correo Electronico  {{login_form.username}}</div>
                                                </div>
                                            </div>
                                        
                                            <div class="row">
                                                <div class="col-md-12">
                                                    <div class="form-group">{{login_form.password.label}}{{login_form.password}}</div>
                                                </div>                                            
                                            </div>
                                                        {% if login_form.errors %}
                                                <div class="col-md-12 d-flex justify-content-center alert alert-danger" role="alert"> Usuario o Contraseña incorrectos. </div>
                                                        {% endif %}

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Iniciar Sesion"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}

mobike/mantenedor_usuario/templates/mantenedor_usuario/register.html
{% extends 'base.html' %}

{% block head %}
<title>
    Registro de Usuario
</title>
{% endblock head %}

{% block content %}
{% if registration_form.non_field_errors %}
    <div class="aler alert-danger" role="alert">
    {% for error in registration_form.non_field_errors %}
        {{error}}
    {% endfor %}
{% endif %}

        <header class="masthead">
        <br>        <br>
            <div class="container"> <div class=" text-center mt-5 ">
                </div>
                <div class="row ">
                    <div class="col-lg-7 mx-auto">
                        <div class="card mt-2 mx-auto p-4 bg-light">
                            <div class="card-body bg-light">
                                <div class="container">
                                    <form role="form" method="POST">
                                        {% csrf_token %}
                                        <div class="controls">
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.username.label}}  {{registration_form.username}} {{registration_form.username.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.email.label}}  {{registration_form.email}} {{registration_form.email.errors}}</div>
                                                </div>
                                            </div>
                                        
                                            <div class="row">
                                                <div class="col-md-4">
                                                    <div class="form-group">{{registration_form.run.label}}  {{registration_form.run}} {{registration_form.run.errors}}</div>
                                                </div>
                                                <div class="col-md-2">
                                                    <div class="form-group">{{registration_form.dv.label}}  {{registration_form.dv}}</div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">{{registration_form.dv.errors}}</div>
                                                </div>                                            
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.first_name.label}} {{registration_form.first_name}} {{registration_form.first_name.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.last_name.label}} {{registration_form.last_name}} {{registration_form.last_name.errors}}</div>
                                                </div>
                                            </div>
                                            <div class="row">
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.password1.label}} {{registration_form.password1}} {{registration_form.password1.errors}}</div>
                                                </div>
                                                <div class="col-md-6">
                                                    <div class="form-group">{{registration_form.password2.label}} {{registration_form.password2}}</div>
                                                </div>
                                                <div class="col-md-12">
                                                    <div class="form-group">{{registration_form.password2.errors}}</div>
                                                </div>

                                                <div class="col-md-12 d-flex justify-content-center"> <input type="submit" class="btn btn-primary" value="Registrarse"> </div>
                                            </div>
                                        </div>
                                    </form>
                                </div>
                            </div>
                        </div> <!-- /.8 -->
                    </div> <!-- /.row-->
                </div>
            </div>
        </header>
<section class='container'>


{% endblock %}