mobike/home/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='home'

urlpatterns = [

    path('', views.index, name='index'),
    path('perfil/', views.perfil, name='perfil'),
    path('agregar_tarjeta/', views.agregarTarjetaCredito, name='agregar_tarjeta'),
    path('seleccionar_arriendo/<str:pk>/', views.seleccionarArriendo, name='seleccionar_arriendo'),
    path('seleccionar_forma_de_pago/<str:pk>/', views.seleccionarFormaDePago, name='seleccionar_forma_de_pago'),
    path('resumen/<str:pk>', views.resumenViaje, name='resumen'),
    path('pago_finalizado/<str:pk>/', views.generarCodigo, name='pago_finalizado'),
    path('desbloquear/<str:pk>/', views.desbloqueoBicicleta, name='desbloquear'),
    path('bloquear/<str:pk>/', views.bloquearBicicleta, name='bloquear'),
]

mobike/mantenedor_usuario/urls.py
from django.contrib import admin
from django.urls import path
from . import views

app_name='mantenedor_usuario'

urlpatterns = [
    path('', views.index, name='index'),
    path('registro/',views.register, name='registro'),
    path('inicio_sesion/',views.login, name='inicio_sesion'),
    path('cerrar_sesion/',views.logout, name='cerrar_sesion'),
    
]

mobike/mobike/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mantenedor_usuario.urls')),
    path('home/', include('home.urls')),
]

mobike/templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
{% block head %}
{% endblock head %}
<head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <link rel="icon" type="image/x-icon" href="{% static '/assets/img/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.1/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Varela+Round" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
</head>
<body>
{% if user.is_authenticated %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a href="{% url 'mantenedor_usuario:index' %}"> <img class="navbar-brand js-scroll-trigger" width="150" src="{% static '/assets/img/header_logo_dark.png' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'home:agregar_tarjeta'%}">Perfil</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="{% url 'mantenedor_usuario:cerrar_sesion'%}">Cerrar Sesion</a></li>
                        </ul>
                    </div>
            </div>
        </nav>
{% else %}
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <div class="container">
                <a href="{% url 'mantenedor_usuario:index' %}"> <img class="navbar-brand js-scroll-trigger" width="150" src="{% static '/assets/img/header_logo_dark.png' %}"></a>
                <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                    <div class="collapse navbar-collapse" id="navbarResponsive">
                        <ul class="navbar-nav ml-auto">
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#about">Que es Mobike</a></li>
                            <li class="nav-item"><a class="nav-link js-scroll-trigger" href="#signup">Registro</a></li>
                        </ul>
                    </div>
            </div>
        </nav>    
{% endif %}
{% block content %}
{% endblock content %}
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
</body>
</html>